Repository abhisek247767/Hello-World, pull requests merged in 2024-10, with the labels that each got.

#3 Improved README.md & Added some basic hello world!
  README.md
  hello_world.go
  hello_world.js
  hello_world.py
Labels: Hacktoberfest

#6 Add hello_world.php script
  hello_world.php
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#10 Updated Hello world in C
  HelloWorld.java
  hello_world.c
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#15 Updated Anchor Links in README
  README.md
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#9 Hello World written in html
  hello_world.html
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#14 Added Hello World in Java, C++ and C#
  hello_world.cpp
  hello_world.cs
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#17 Add hello_world.rs
  hello_world.rs
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#20 Create hello_world.ts
  hello_world.ts
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#26 Create hello_world.swift
  hello_world.swift
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#29 Create hello_world.dart
  hello_world.dart
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#28 Lua programming language
  hello_world.lua
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#30 hello world in scala
  hello_world.scala
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#18 Adding Hello World Ruby File
  hello_world.rb
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#32 Written Hello World in Objective C and R Programming
  hello_world.h
  hello_world.r
Labels: good first issue, Hacktoberfest-accepted, Hacktoberfest-2024

#34 Create hello_world.exs
  hello_world.exs
Labels: good first issue, Hacktoberfest-accepted, Hacktoberfest-2024

#37 Create hello_world.jl
  hello_world.jl
Labels: Hacktoberfest, Hacktoberfest-2024

#38 add: hello world in bash code
  hello_world.sh
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#33 hello_world: Svelte
  hello_world.svelte
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#39 Hello world in kotlin
  hello_world.kt
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#42 hello world .tsx
  hello_world.tsx
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#41 Added "Hello World" to Vue.Js language
  hello_world.vue
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#40 Create hello_world.cbl
  hello_world.cbl
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#46 Create hello_world.erl
  hello_world.erl
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#43 Created helloworld.hs
  helloworld.hs
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#44 Hacktober Hello_world
  Hello_World.java
  Hello_World1.java
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#47 Created hello_world.bf
  hello_world.bf
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#45 Create hello_world.bhai
  hello_world.bhai
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#67 Created hello_world.pl
  hello_world.pl
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#58 Create hello_world.hs
  hello_world.hs
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#80 Create hello_world.vbs
  hello_world.vbs
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#69 Created hello_world.tcl
  hello_world.tcl
Labels: good first issue, Hacktoberfest, Hacktoberfest-2024

#81 Created hello_world.pas
  hello_world.pas
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#50 Hello World in assembly language
  hello_world.asm
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#84 Create hello.pl
  hello.pl
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#66 Create hello_world.lol
  hello_world.lol
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#90 Created hello_world.fs
  hello_world.fs
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024, Feedback

#94 Nim: added hello world in nim
  hello_world.nim
Labels: Hacktoberfest-accepted, Hacktoberfest-2024

#56 Create helloWorld.m
  hello_world.m
Labels: good first issue, Hacktoberfest, Hacktoberfest-2024

#71 Create helloworld.st
  hello_world.st
Labels: good first issue, Hacktoberfest, Hacktoberfest-2024

#61 Create hello_world.chef
  hello_world.chef
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#72 Create helloworld.ahk
  hello_world.ahk
Labels: good first issue, Hacktoberfest, Hacktoberfest-2024

#82 Created hello_world.f90
  hello_world.f90
Labels: good first issue, Hacktoberfest, Hacktoberfest-2024

#100 Add Hello World Example in Céu Language
  hello_world.ceu
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#91 Hello_world in "V" Language
  hello_world.v
Labels: good first issue, Hacktoberfest-accepted, Hacktoberfest-2024

#103 Create hello_world.raku
  hello_world.raku
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#109 Added "Hello World" in Elixir Language
  hello_world.exs
Labels: good first issue, Hacktoberfest, Hacktoberfest-2024

#112 Add hello world program in REXX programming language
  hello_world.rexx
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024

#114 add Hello World in Crystal programming language
  hello_world.cr
Labels: good first issue, Hacktoberfest, Hacktoberfest-2024

#115 Hello World added in Pike language
  hello_world.pike
Labels: Hacktoberfest, Hacktoberfest-2024

#116 Add Hello, World! in Racket Langauge
  hello_world.rkt
Labels: enhancement, Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024, Feedback

#117 Create Hello_World.zig
  Hello_World.zig
Labels: good first issue, Hacktoberfest, Hacktoberfest-2024

#74 Add Hello World in Groovy language
  hello_world.groovy
Labels: good first issue, Hacktoberfest

#106 Added hello_world in Ada Language
  hello_world.ada
Labels: Hacktoberfest, Hacktoberfest-accepted, Hacktoberfest-2024
